random-filter-s:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": 'yfcc10M-filters.pkl', 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 60000,
              "beam_widths": [70, 70, 70]
              }]

yfcc-10M:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": "yfcc10M-filters.pkl", 
              "historical_filters_percentage": 1,
              "is_and": "True",
              "M": 16,
              "ef_construction": 40,
              "index_budget": 0.5,
              "bitvector_cutoff": 1000,
              "workload_window_size": 100000,
              "heterogeneous_indexing": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10},
            {"ef_search": 20},
            {"ef_search": 30},
            {"ef_search": 40},
            {"ef_search": 50},
            {"ef_search": 60},
            {"ef_search": 70},
            {"ef_search": 80},
            {"ef_search": 90},
            {"ef_search": 100},
            {"ef_search": 110}]

paper:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": "paper-filters.pkl", 
              "historical_filters_percentage": 1,
              "is_and": "True",
              "M": 32,
              "ef_construction": 40,
              "index_budget": 0.5,
              "bitvector_cutoff": 1000,
              "workload_window_size": 100000,
              "heterogeneous_indexing": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10},
            {"ef_search": 20},
            {"ef_search": 30},
            {"ef_search": 40},
            {"ef_search": 50},
            {"ef_search": 60},
            {"ef_search": 70},
            {"ef_search": 80},
            {"ef_search": 90},
            {"ef_search": 100},
            {"ef_search": 110}]


uqv:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": "uqv_query_attrs.pkl",
              "historical_filters_percentage": 1,
              "is_and": "False",
              "M": 32,
              "ef_construction": 40,
              "index_budget": 0.5,
              "bitvector_cutoff": 1000,
              "workload_window_size": 100000,
              "heterogeneous_indexing": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10},
            {"ef_search": 20},
            {"ef_search": 30},
            {"ef_search": 40},
            {"ef_search": 50},
            {"ef_search": 60},
            {"ef_search": 70},
            {"ef_search": 80},
            {"ef_search": 90},
            {"ef_search": 100},
            {"ef_search": 110}]

sift:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": "sift_query_attrs.pkl",
              "historical_filters_percentage": 1,
              "is_and": "False",
              "M": 32,
              "ef_construction": 40,
              "index_budget": 0.5,
              "bitvector_cutoff": 1000,
              "workload_window_size": 100000,
              "heterogeneous_indexing": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10},
            {"ef_search": 20},
            {"ef_search": 30},
            {"ef_search": 40},
            {"ef_search": 50},
            {"ef_search": 60},
            {"ef_search": 70},
            {"ef_search": 80},
            {"ef_search": 90},
            {"ef_search": 100},
            {"ef_search": 110}]


msong:
    mymethod0times100percent:
      docker-tag: neurips23-filter-mymethod0times100percent
      module: neurips23.filter.mymethod0times100percent.mymethod0times100percent
      constructor: MyMethod0Times100Percent
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": "msong_query_attrs.pkl",
              "historical_filters_percentage": 1,
              "is_and": "False",
              "M": 32,
              "ef_construction": 40,
              "index_budget": 0.5,
              "bitvector_cutoff": 200,
              "workload_window_size": 100000,
              "heterogeneous_indexing": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10},
            {"ef_search": 20},
            {"ef_search": 30},
            {"ef_search": 40},
            {"ef_search": 50},
            {"ef_search": 60},
            {"ef_search": 70},
            {"ef_search": 80},
            {"ef_search": 90},
            {"ef_search": 100},
            {"ef_search": 110}]
