random-filter-s:
    caps:
      docker-tag: neurips23-filter-caps
      module: neurips23.filter.caps.caps
      constructor: Caps
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 5000, 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 60000,
              "beam_widths": [70, 70, 70]
              }]

paper:
    caps:
      docker-tag: neurips23-filter-caps
      module: neurips23.filter.caps.caps
      constructor: Caps
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "True",
              "num_clusters": 1000,
              "bruteforce_selectivity_threshold": 0.005,
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 3000},
            {"ef_search": 6000},
            {"ef_search": 9000},
            {"ef_search": 12000},
            {"ef_search": 15000},
            {"ef_search": 18000},
            {"ef_search": 21000},
            {"ef_search": 24000},
            {"ef_search": 27000},
            {"ef_search": 30000},
            {"ef_search": 33000},
            {"ef_search": 36000}]

sift:
    caps:
      docker-tag: neurips23-filter-caps
      module: neurips23.filter.caps.caps
      constructor: Caps
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "True",
              "num_clusters": 100,
              "bruteforce_selectivity_threshold": 0.005,
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 3000},
            {"ef_search": 6000},
            {"ef_search": 9000},
            {"ef_search": 12000},
            {"ef_search": 15000},
            {"ef_search": 18000},
            {"ef_search": 21000},
            {"ef_search": 24000},
            {"ef_search": 27000},
            {"ef_search": 30000},
            {"ef_search": 33000},
            {"ef_search": 36000}]


msong:
    caps:
      docker-tag: neurips23-filter-caps
      module: neurips23.filter.caps.caps
      constructor: Caps
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "True",
              "num_clusters": 1000,
              "bruteforce_selectivity_threshold": 0.005,
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 3000},
            {"ef_search": 6000},
            {"ef_search": 9000},
            {"ef_search": 12000},
            {"ef_search": 15000},
            {"ef_search": 18000},
            {"ef_search": 21000},
            {"ef_search": 24000},
            {"ef_search": 27000},
            {"ef_search": 30000},
            {"ef_search": 33000},
            {"ef_search": 36000}]
