random-filter-s:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"historical_filters_file": 'yfcc10M-filters.pkl', 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 60000,
              "beam_widths": [70, 70, 70]
              }]

yfcc-10M:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "True",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10}]

paper:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "True",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10}]

uqv:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10}]


sift:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 10}]


msong:
    prefilter:
      docker-tag: neurips23-filter-prefilter
      module: neurips23.filter.prefilter.prefilter
      constructor: Prefilter
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"is_and": "False",
              "num_index_construction_threads": 96
            }]
          query-args: |
            [{"ef_search": 20}]
