random-filter-s:
    acorn:
      docker-tag: neurips23-filter-acorn
      module: neurips23.filter.acorn.acorn
      constructor: Acorn
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 5000, 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"target_points": 15000,
              "tiny_cutoff": 60000,
              "beam_widths": [70, 70, 70]
              }]

yfcc-10M:
    acorn:
      docker-tag: neurips23-filter-acorn
      module: neurips23.filter.acorn.acorn
      constructor: Acorn
      base-args: ["@metric"]
      run-groups:
        base:
          args: |
            [{"cluster_size": 5000, 
              "T": 8,
              "cutoff": 10000,
              "max_iter": 10,
              "weight_classes": [100000, 400000],
              "build_params": [{"max_degree": 8,
                                "limit": 200,
                                "alpha": 1.175},
                              {"max_degree": 10,
                               "limit": 200,
                               "alpha": 1.175},
                              {"max_degree": 12,
                               "limit": 200,
                               "alpha": 1.175}],
              "bitvector_cutoff": 10000
            }]
          query-args: |
            [{"bitvector_cutoff": 602,
              "budget": 10000000
              }]
